export const PRODUCTS = 'PRODUCTS';
export const PRODUCTSREQUESTED = 'PRODUCTSREQUESTED';
export const ADDTOCART_COUNT = 'ADDTOCART_COUNT';
export const REMOVETOCART_COUNT = 'REMOVETOCART_COUNT';
export const REMOVEPRODUCTTOCART_COUNT = 'REMOVEPRODUCTTOCART_COUNT';
export const REMOVEALLPRODUCTTOCART_COUNT = 'REMOVEALLPRODUCTTOCART_COUNT';
export const CATEGORIS = 'CATEGORIS';